In [1]:
import pandas as pd

df = pd.read_csv('dataset/homeprices-one_hot_encoding.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [2]:
dummies_df = pd.get_dummies(df.town)  # u can pass the df directly too
dummies_df

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [3]:
pd.get_dummies(df)

area   price  town_monroe township  town_robinsville  town_west windsor
0   2600  550000                     1                 0                  0
1   3000  565000                     1                 0                  0
2   3200  610000                     1                 0                  0
3   3600  680000                     1                 0                  0
4   4000  725000                     1                 0                  0
5   2600  585000                     0                 0                  1
6   2800  615000                     0                 0                  1
7   3300  650000                     0                 0                  1
8   3600  710000                     0                 0                  1
9   2600  575000                     0                 1                  0
10  2900  600000                     0                 1                  0
11  3100  620000                     0                 1                  0
12  3600  695000                     0                 1                  0

In [4]:
_X = pd.concat([df, dummies_df], axis=1)
y = df['price']
X = _X.drop(['price', 'west windsor', 'town'],
            axis=1)  # droping town_monroe township to prevent Multicolinearity, dummy variable trap (derivable stuff)
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [5]:
from sklearn.linear_model import LinearRegression

m = LinearRegression()
m.fit(X, y)

LinearRegression()

In [6]:
label = {"monroe": [0, 0], 'robinsville': [0, 1], 'ww': [1, 1]}
area = 3000
other = label["monroe"]
m.predict([[area, *other]])

/Users/hiro/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([630482.69189422])

In [7]:
m.score(X, y)

0.9573929037221873

Sklearn's One Hot encoder to do the same thing

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [9]:
df_le = df.copy()
df_le.town = le.fit_transform(df_le.town)
df_le

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [13]:
X = df_le.drop(['price'], axis=1)
y = df_le['price']
X

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [27]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   town    13 non-null     category
 1   area    13 non-null     int64   
dtypes: category(1), int64(1)
memory usage: 377.0 bytes


In [36]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()  #TODO: categories
X['town'] = X['town'].astype('category')

X_ = ohe.fit_transform(X[['town', 'area']]).toarray()
X.join(pd.DataFrame(X_))

town  area    0    1    2    3    4    5    6    7    8    9   10   11
0     0  2600  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0  3000  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2     0  3200  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
3     0  3600  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0  4000  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
5     2  2600  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6     2  2800  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7     2  3300  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
8     2  3600  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
9     1  2600  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10    1  2900  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
11    1  3100  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
12    1  3600  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0

In [37]:
ohe.fit_transform(X.values)

<13x12 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder='passthrough')
X_ct = ct.fit_transform(X)
X_ct

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [52]:
X_ct = X_ct[:, 1:]  # removing one of the towns to prevent dummy variable trap
X_ct

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [53]:
from sklearn.linear_model import LinearRegression

m = LinearRegression()
m.fit(X_ct, y)

LinearRegression()

In [55]:
m.predict([[1, 0, 2800]])

array([590775.63964739])

Exercise